name: PR Validation

on:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}
        fetch-depth: 0

    - name: Build the Docker image
      run: |
              docker build . --file ./AiHelpBot/Dockerfile
